import pandas as pd
from xml.etree.ElementTree import Element, SubElement, Comment, tostring
import datetime
from xml.dom import minidom
from xml.etree import ElementTree
from excelimport import ExcelImporter


class Buildetwork(object):

    def __init__(self):
        self.my_filetypes = [('Excel File', 'xlsx'), ('Excel file', 'xlx')]
        self.sheet_bridge_domain = 'bridge_domain'
        self.sheet_bd_subnet = 'bd_subnet'
        self.sheet_bd_l3out = 'bd_l3out'
        self.sheet_contract = 'contract'
        self.sheet_epg = 'end_point_group'
        self.sheet_epg_subnet = 'epg_subnet'
        self.sheet_epg_domain_ass = 'epg_domain_association'
        self.xl_file = ExcelImporter().import_excelfile()



    def create_bridge_domain(self):
        # Bridge SpreadSheet
        excel_file = self.xl_file
        bridge_domain_sheet = pd.read_excel(excel_file,sheet_name=self.sheet_bridge_domain)
        bd_subnet_sheet = pd.read_excel(excel_file, sheet_name=self.sheet_bd_subnet)
        bd_l3out_sheet = pd.read_excel(excel_file, sheet_name=self.sheet_bd_l3out)
        set_of_tenants = set()
        results = []

        for index, row in bridge_domain_sheet.iterrows():
            if row['status'] == 'ignored':
                continue
            else:
                set_of_tenants.add(row['tenant'])

        print(set_of_tenants)


        for tenant in set_of_tenants:
            root = Element('polUni')
            # root.set('version', '1.0')
            root.append(Comment('Generated by JTools UCI Builder'))
            self.fvTenant = SubElement(root, 'fvTenant', {'name': tenant, 'status': 'modified'})
            for index, row in bridge_domain_sheet.iterrows():
                if row['status'] == 'ignored':
                    continue
                else:
                    if row['tenant'] == tenant:
                        fvBD = SubElement(self.fvTenant, 'fvBD', {'arpFlood': 'yes','descr': row['description'],
                                                                  'ipLearning':'yes', 'limitIpLearnToSubnets':'yes',
                                                                  'mcastAllow':'no','multiDstPktAct':'bd-flood',
                                                                  'name':row['name'], 'status':'', 'type':'regular',
                                                                  'unicastRoute':'yes', 'unkMacUcastAct':'flood',
                                                                  'unkMcastAct':'flood'})
                        fvRsBDToNdP = SubElement(fvBD,'fvRsBDToNdP',{'tnNdIfPolName':''})
                        fvRsCtx = SubElement(fvBD,'fvRsCtx', {'tnFvCtxName':row['vrf']})
                        fvRsIgmpsn = SubElement(fvBD,'fvRsIgmpsn',{'tnIgmpSnoopPolName':''})
                        fvRsBdToEpRet = SubElement(fvBD,'fvRsBdToEpRet',{'resolveAct':'resolve',
                        'tnFvEpRetPolName':''})
                        for index, row_ip in bd_subnet_sheet.iterrows():
                            if row_ip['bridge_domain'] == row['name']:
                                fvSubnet = SubElement(fvBD, 'fvSubnet', {'ctrl': '','descr':row_ip['description'],
                                                                         'ip':row_ip['bd_subnet'],'preferred':'no',
                                                                         'scope':'public','virtual':'no'})
                        for index, row_l3 in bd_l3out_sheet.iterrows():
                            if row_l3['bd_name'] == row['name']:
                                fvRsBDToOut = SubElement(fvBD, 'fvRsBDToOut', {'tnL3extOutName':row_l3['l3out_name']})
            results.append(root)
        for result in results:
            print(ExcelImporter().prettify(result))
        return results

    def generate_xml_files(self):
        pass


    def create_contract(self):
        # contract SpreadSheet
        excel_file = Buildetwork().import_excelfile()
        contract_sheet = pd.read_excel(excel_file,sheet_name=self.sheet_contract)
        set_of_tenants = set()
        results = []

        for index, row in contract_sheet.iterrows():
            if row['status'] == 'ignored':
                continue
            else:
                set_of_tenants.add(row['tenant'])

        print(set_of_tenants)

        
        for tenant in set_of_tenants:
            root = Element('polUni')
            # root.set('version', '1.0')
            root.append(Comment('Generated by JTools UCI Builder'))
            self.fvTenant = SubElement(root, 'fvTenant', {'name': tenant, 'status': 'modified'})
            for index, row in contract_sheet.iterrows():
                if row['status'] == 'ignored':
                    continue
                else:
                    if row['tenant'] == tenant:
                        vzBrCP = SubElement(self.fvTenant, 'vzBrCP', {'descr': row['description'],
                                                                  'name':row['name'], 'nameAlias':'', 'prio':'unspecified',
                                                                  'scope':row['scope'], 'status':'',
                                                                  'targetDscp':'unspecified'})
            results.append(root)
        for result in results:
            print(Buildetwork().prettify(result))

     
        return results


    def create_epg(self):
        # Bridge SpreadSheet
        excel_file = Buildetwork().import_excelfile()
        epg_sheet = pd.read_excel(excel_file,sheet_name=self.sheet_epg)
        epg_subnet_sheet = pd.read_excel(excel_file, sheet_name=self.sheet_epg_subnet)
        epg_domain_ass_sheet = pd.read_excel(excel_file, sheet_name=self.sheet_epg_domain_ass)
        set_of_tenants = set()
        epg_dom_vmm = 'vmm_vmware'
        epg_dom_phy = 'physical'
        epg_dom = ''
        epg_vmm_tDn = ''
        epg_phy_tDN = ''
        results = []

        for index, row in epg_sheet.iterrows():
            if row['status'] == 'ignored':
                continue
            else:
                set_of_tenants.add(row['tenant'])

        print(set_of_tenants)


        for tenant in set_of_tenants:
            root = Element('polUni')
            # root.set('version', '1.0')
            root.append(Comment('Generated by JTools UCI Builder'))
            self.fvTenant = SubElement(root, 'fvTenant', {'name': tenant, 'status': 'modified'})
            for index, row in epg_sheet.iterrows():
                if row['status'] == 'ignored':
                    continue
                else:
                    if row['tenant'] == tenant:
                        fvAEPg = SubElement(self.fvTenant, 'fvAEPg', {'descr': row['description'],
                                                                  'floodOnEncap':'disabled', 'isAttrBasedEPg':'no',
                                                                  'matchT':'AtleastOne','name':row['name'], 'pcEnfPref':'unenforced', 'prefGrMemb':'exclude',
                                                                  'prio':'unspecified', 'status':''})
                        fvRsBd = SubElement(fvAEPg,'fvRsBd',{'tnFvBDName':row['bridge_domain']})
                        for index, row_ip in epg_subnet_sheet.iterrows():
                            if row_ip['epg'] == row['name'] and row_ip['tenant'] == row['tenant']:
                                fvSubnet = SubElement(fvAEPg,'fvSubnet',{'ctrl':'no-default-gateway','descr':row_ip['description'],
                                                                    'ip':row_ip['epg_subnet'],'preferred':'no','scope':row_ip['subnet_scope'],
                                                                    'virtual':'no'})
                        for index, row_domain in epg_domain_ass_sheet.iterrows():
                            if row_domain['epg_name'] == row['name'] and row_domain['tenant'] == row['tenant'] and row_domain['domainType'] == epg_dom_vmm:
                                epg_dom = row_domain['domainName']
                                epg_vmm_tDn = 'uni/vmmp-VMware/dom-' + epg_dom
                                epg_phy_tDN = 'uni/phys-' + epg_dom
                                fvRsDomAtt_vmm = SubElement(fvAEPg,'fvRsDomAtt',{'encap':'','encapMode':'auto','epgCos':'Cos0','epgCosPref':'disabled',
                                                                    'instrImedcy':'immediate','netflowDir':'both','netflowPref':'disabled',
                                                                    'primaryEncap':'unknown','primaryEncapInner':'unknown','resImedcy':'immediate',
                                                                    'secondaryEncapInner':'unknown','status':'','switchingMode':'native','tDn':epg_vmm_tDn})
                                vmmSecP = SubElement(fvRsDomAtt_vmm,'vmmSecP',{'allowPromiscuous':'reject','descr':'','forgedTransmits':'reject',
                                                                    'macChanges':'reject','name':''})                       
                                fvRsDomAtt_phy = SubElement(fvAEPg,'fvRsDomAtt',{'instrImedcy':'immediate','resImedcy':'immediate',
                                                                    'status':'','tDn':epg_phy_tDN})
            results.append(root)
        for result in results:
            print(Buildetwork().prettify(result))
        return results
    

#Buildetwork().create_bridge_domain()

#Buildetwork().create_contract()

Buildetwork().create_epg()



